{application,evins,
             [{description,"EvoLogics intelligent Networking Software framework"},
              {vsn,string:chomp(os:cmd("git describe --abbrev=0"))},
              {id,string:chomp(os:cmd("git describe"))},
              {modules,[]},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{fsm_app,["/usr/local/etc/fsm.conf"]}},
              {start_phases,[]}]}.
